language: node_js
node_js:
  - "4"
services:
  - mongodb
addons:
  packages:
    - gcc-4.8
    - g++-4.8
env:
  - CXX=g++-4.8
sudo: required
before_script:
  - npm install -g eslint mocha chai
script:
  - eslint $(find . -name '*.js' | grep -v 'node_modules')
  - mocha
